In [1]:
!pip3 install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/alisiyakhaliulina/Library/Python/3.12/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/alisiyakhaliulina/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [2]:
import nltk

nltk.internals.config_java(options='-Djava.security.manager', verbose=False)

nltk.download()

nltk.internals.config_java(options='-Djava.security.manager', verbose=False)

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

In [3]:
import requests

# Получение стоп-слов с удаленного ресурса
stopwords_url = "https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/stopwords.zip"
response = requests.get(stopwords_url)

# Сохранение содержимого в локальный файл
with open("stopwords.zip", "wb") as file:
    file.write(response.content)

# Распаковка ZIP-архива
import zipfile
with zipfile.ZipFile("stopwords.zip", "r") as zip_ref:
    zip_ref.extractall("./nltk_data/corpora")

# Использование стоп-слов из NLTK
from nltk.corpus import stopwords
print(stopwords.words('russian'))

['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его', 'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от', 'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'вдруг', 'ли', 'если', 'уже', 'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'опять', 'уж', 'вам', 'ведь', 'там', 'потом', 'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их', 'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда', 'кто', 'этот', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'здесь', 'этом', 'один', 'почти', 'мой', 'тем', 'чтобы', 'нее', 'сейчас', 'были', 'куда', 'зачем', 'всех', 'никогда', 'можно', 'при', 'наконец', 'два', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них', 'какая', 'много', 'разве', 'три', 'эту', 'моя', 'впрочем', 'хорошо', 'свою', 'этой', 'перед', 'иногда', 'лучше', 'чуть', 'том', 'нельзя', 'такой', 'им', 'более', 'всегда', 'конечно', 'всю', 'между']

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('SMSSpamCollection', sep = '\t')

In [6]:
df.head()

,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
0,ham,Ok lar... Joking wif u oni...
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...
2,ham,U dun say so early hor... U c already then say...
3,ham,"Nah I don't think he goes to usf, he lives aro..."
4,spam,FreeMsg Hey there darling it's been 3 week's n...

In [7]:
df.columns = ['Labell', 'Text']

In [8]:
df

     Labell                                               Text
0       ham                      Ok lar... Joking wif u oni...
1      spam  Free entry in 2 a wkly comp to win FA Cup fina...
2       ham  U dun say so early hor... U c already then say...
3       ham  Nah I don't think he goes to usf, he lives aro...
4      spam  FreeMsg Hey there darling it's been 3 week's n...
...     ...                                                ...
5566   spam  This is the 2nd time we have tried 2 contact u...
5567    ham               Will ü b going to esplanade fr home?
5568    ham  Pity, * was in mood for that. So...any other s...
5569    ham  The guy did some bitching but I acted like i'd...
5570    ham                         Rofl. Its true to its name

[5571 rows x 2 columns]