In [4]:
!pip3 install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/alisiyakhaliulina/Library/Python/3.12/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/alisiyakhaliulina/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip3 install --upgrade pip

In [8]:
import nltk

nltk.internals.config_java(options='-Djava.security.manager', verbose=False)

nltk.download()

nltk.internals.config_java(options='-Djava.security.manager', verbose=False)

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

In [ ]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

stop_words = stopwords.words('english')

OSError: [Errno 30] Read-only file system: '/path'

In [6]:
import pandas as pd

In [8]:
df = pd.read_csv('SMSSpamCollection', sep = '\t')

In [10]:
df.head()

,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
0,ham,Ok lar... Joking wif u oni...
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...
2,ham,U dun say so early hor... U c already then say...
3,ham,"Nah I don't think he goes to usf, he lives aro..."
4,spam,FreeMsg Hey there darling it's been 3 week's n...

In [13]:
df.columns = ['Labell', 'Text']

In [14]:
df

     Labell                                               Text
0       ham                      Ok lar... Joking wif u oni...
1      spam  Free entry in 2 a wkly comp to win FA Cup fina...
2       ham  U dun say so early hor... U c already then say...
3       ham  Nah I don't think he goes to usf, he lives aro...
4      spam  FreeMsg Hey there darling it's been 3 week's n...
...     ...                                                ...
5566   spam  This is the 2nd time we have tried 2 contact u...
5567    ham               Will ü b going to esplanade fr home?
5568    ham  Pity, * was in mood for that. So...any other s...
5569    ham  The guy did some bitching but I acted like i'd...
5570    ham                         Rofl. Its true to its name

[5571 rows x 2 columns]